# Generated by Django 5.2.7 on 2026-05-16 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_patient_staff_remove_registration_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='queue_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
