# Generated by Django 5.2.7 on 2026-05-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_alter_queue_queue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='barangay',
            field=models.CharField(default='Not Specified', max_length=100),
        ),
    ]
