# Generated by Django 5.2.7 on 2026-05-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_patient_barangay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='Waiting', max_length=20),
        ),
    ]
